'use client';

import { useEffect, useMemo, useState } from 'react';
import type { UnverifiedReason, Verdict } from '../lib/verdict';

interface Evidence {
  title: string;
  source: string;
  link: string;
}

interface Analysis {
  verdict: Verdict;
  sourceCount: number;
  addressHits: number;
  reason?: UnverifiedReason;
  matches: Evidence[];
}

/**
 * Deliberately no "safe" or "all clear" wording anywhere.
 *
 * A scam listing built from AI-generated photos returns zero reverse-image
 * matches, which is the same signal as a genuine photo nobody has syndicated.
 * Absence of corroboration is not evidence of honesty, and copy that implies
 * otherwise is the one failure that could cost someone a deposit.
 */
const COPY: Record<Verdict, { heading: string; body: string }> = {
  CORROBORATED: {
    heading: 'Address corroborated',
    body:
      'These photos appear elsewhere online alongside the same address. That is what a genuine, ' +
      'syndicated listing looks like. It is not a guarantee — keep verifying the landlord separately.',
  },
  CONTRADICTED: {
    heading: 'Address not found on any copy',
    body:
      'These photos are published widely, but not one of those listings carries the address you were ' +
      'given. Hijacked listings look exactly like this: real photos lifted from a real property, ' +
      'relabelled with a different address. Check the sources below before sending any money.',
  },
  UNVERIFIED: {
    heading: 'Not enough evidence',
    body:
      'We could not find enough copies of these photos to judge the address either way. This is not a ' +
      'pass: photos generated by AI, or taken by the landlord and posted nowhere else, both land here.',
  },
};

/**
 * Shown instead of the UNVERIFIED copy when the address, not the evidence, was
 * the problem. Saying "not enough copies" above a list of copies we did find
 * reads as a malfunction and leaves the user no way to correct their input.
 */
const UNREADABLE_ADDRESS = {
  heading: 'We could not read that address',
  body:
    'The check needs a street number and street name — for example "13505 Burnet Rd". We did not ' +
    'run the address comparison, so nothing below says anything about this listing either way.',
};

const ERRORS: Record<string, string> = {
  invalid_token: 'That upload is no longer valid. Select the photo again.',
  rate_limited: 'Too many checks from this address. Try again in a little while.',
  quota: 'The search quota for this demo is exhausted. Try again next month.',
  auth: 'The search service rejected our credentials. This is our problem, not yours.',
  transport: 'The search service did not respond. Try again in a moment.',
  unknown: 'The search service returned something we could not read.',
  not_configured: 'This deployment is missing its API configuration.',
  invalid_image_url: 'That image is not one we stored. Upload the photo again.',
  address_too_long: 'That address is too long. Enter just the street address.',
  unsupported_type: 'Upload a JPEG, PNG, or WebP photo.',
  too_large: 'That photo is too large. 4 MB is the limit.',
  length_required: 'The upload was rejected. Try selecting the photo again.',
  empty: 'That file appears to be empty.',
  storage_unavailable: 'We could not store the photo. Try again in a moment.',
  bad_request: 'Something about that request was malformed.',
};

function message(code: unknown): string {
  return (typeof code === 'string' && ERRORS[code]) || 'Something went wrong. Try again.';
}

/**
 * Parse a response body that may not be JSON at all.
 *
 * Platform errors — a 413 raised above the app, a gateway 502, a framework
 * error page — arrive as HTML. Letting `.json()` throw sent those to the
 * network-failure branch, telling people to check a connection that was fine.
 */
async function readJson(res: Response): Promise<{ [k: string]: unknown } | null> {
  try {
    return (await res.json()) as { [k: string]: unknown };
  } catch {
    return null;
  }
}

export default function Home() {
  const [file, setFile] = useState<File | null>(null);
  const [address, setAddress] = useState('');
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [result, setResult] = useState<Analysis | null>(null);

  // Derived once per file, not once per render. Called inline in the JSX it
  // minted a new object URL on every keystroke, each one pinning the whole File
  // until the page unloaded.
  const previewUrl = useMemo(() => (file ? URL.createObjectURL(file) : null), [file]);
  useEffect(() => {
    if (!previewUrl) return;
    return () => URL.revokeObjectURL(previewUrl);
  }, [previewUrl]);

  async function check(e: React.FormEvent) {
    e.preventDefault();
    if (!file) return;

    setBusy(true);
    setError(null);
    setResult(null);

    try {
      // The photo is stored first because Google Lens takes a URL and cannot be
      // handed an upload; /api/analyze deletes the blob once the lookup returns.
      const stored = await fetch('/api/upload', { method: 'POST', body: file });
      if (!stored.ok) {
        const body = await readJson(stored);
        // A 413 raised by the platform has no JSON body to name the cause, but
        // the status alone is enough to say the right thing.
        setError(message(body?.error ?? (stored.status === 413 ? 'too_large' : undefined)));
        return;
      }
      const blob = await readJson(stored);
      if (typeof blob?.url !== 'string') {
        setError(message(undefined));
        return;
      }

      const res = await fetch('/api/analyze', {
        method: 'POST',
        headers: { 'content-type': 'application/json' },
        body: JSON.stringify({ imageUrl: blob.url, token: blob.token, address }),
      });
      if (!res.ok) {
        const body = await readJson(res);
        setError(message(body?.error));
        return;
      }
      const data = await readJson(res);
      if (!data) {
        setError(message(undefined));
        return;
      }
      setResult(data as unknown as Analysis);
    } catch {
      setError('Could not reach the server. Check your connection and try again.');
    } finally {
      setBusy(false);
    }
  }

  return (
    <main>
      <h1>DepositCheck</h1>
      <p className="lede">
        Before you wire a deposit, check whether the listing&rsquo;s photos actually belong to the
        address you were given.
      </p>

      <form onSubmit={check}>
        <label htmlFor="photo">
          Listing photo
          <span className="hint"> — screenshot or save one image from the listing</span>
        </label>
        <input
          id="photo"
          type="file"
          accept="image/jpeg,image/png,image/webp"
          required
          onChange={(e) => setFile(e.target.files?.[0] ?? null)}
        />
        {previewUrl && (
          // eslint-disable-next-line @next/next/no-img-element -- a local object URL, not a remote asset
          <img className="preview" src={previewUrl} alt="The photo you selected" />
        )}

        <label htmlFor="address">
          Address you were given
          <span className="hint"> — street number and street name are what matter</span>
        </label>
        <input
          id="address"
          type="text"
          maxLength={200}
          placeholder="13505 Burnet Rd, Austin TX"
          value={address}
          onChange={(e) => setAddress(e.target.value)}
        />

        <button type="submit" disabled={busy || !file}>
          {busy ? 'Checking…' : 'Check this listing'}
        </button>
      </form>

      {error && <p className="error">{error}</p>}

      {result && (
        <>
          <section className="result" data-verdict={result.verdict}>
            <h2>
              {result.reason === 'unreadable_address'
                ? UNREADABLE_ADDRESS.heading
                : COPY[result.verdict].heading}
            </h2>
            <p>
              {result.reason === 'unreadable_address'
                ? UNREADABLE_ADDRESS.body
                : COPY[result.verdict].body}
            </p>
          </section>

          {result.reason !== 'unreadable_address' && result.matches.length > 0 && (
            <section className="evidence">
              <h3>
                Found on {result.sourceCount} {result.sourceCount === 1 ? 'site' : 'sites'} ·{' '}
                {result.addressHits} {result.addressHits === 1 ? 'listing names' : 'listings name'} your
                address
              </h3>
              <ol>
                {result.matches.map((m, i) => (
                  <li key={`${m.link}-${i}`}>
                    {m.link ? (
                      <a href={m.link} target="_blank" rel="noreferrer noopener">
                        {m.title || m.link}
                      </a>
                    ) : (
                      m.title
                    )}
                    {m.source && <span className="src"> — {m.source}</span>}
                  </li>
                ))}
              </ol>
            </section>
          )}
        </>
      )}
    </main>
  );
}
