'use client';

import { useEffect, useMemo, useState } from 'react';
import { addressAppearsIn } from '../lib/address';
import type { UnverifiedReason, Verdict } from '../lib/verdict';

interface Evidence {
  title: string;
  source: string;
  link: string;
}

interface Analysis {
  verdict: Verdict;
  sourceCount: number;
  addressHits: number;
  reason?: UnverifiedReason;
  /** Set only on CONTRADICTED: the address the photos were found published as. */
  contradictingAddress?: string;
  matches: Evidence[];
}

/**
 * Deliberately no "safe" or "all clear" wording anywhere.
 *
 * A scam listing built from AI-generated photos returns zero reverse-image
 * matches, which is the same signal as a genuine photo nobody has syndicated.
 * Absence of corroboration is not evidence of honesty, and copy that implies
 * otherwise is the one failure that could cost someone a deposit.
 */
const COPY: Record<Verdict, { heading: string; body: string }> = {
  CORROBORATED: {
    heading: 'Address corroborated',
    body:
      'These photos appear elsewhere online alongside the same address. That is what a genuine, ' +
      'syndicated listing looks like. It is not a guarantee — keep verifying the landlord separately.',
  },
  CONTRADICTED: {
    heading: 'These photos belong to a different address',
    body:
      'The listings carrying these photos name one specific property, and it is not the address you ' +
      'were given. Hijacked listings look exactly like this: real photos lifted from a real property, ' +
      'relabelled with a different address. Check the sources below before sending any money.',
  },
  UNVERIFIED: {
    heading: 'Not enough evidence',
    body:
      'We could not find enough copies of these photos to judge the address either way. This is not a ' +
      'pass: photos generated by AI, or taken by the landlord and posted nowhere else, both land here.',
  },
};

/**
 * Shown instead of the generic UNVERIFIED copy when we know *why* we could not
 * judge. "Not enough evidence" above a list of evidence reads as a malfunction,
 * and leaves the user no idea what to do differently.
 */
const REASON_COPY: Record<UnverifiedReason, { heading: string; body: string }> = {
  unreadable_address: {
    heading: 'We could not read that address',
    body:
      'The check needs a street number and street name — for example "13505 Burnet Rd". We did not ' +
      'run the address comparison, so nothing below says anything about this listing either way.',
  },
  generic_photo: {
    heading: 'This photo cannot identify a property',
    body:
      'The same photo is published under several different addresses, which is normal for an ' +
      'apartment building: one staged marketing shot is reused for every unit and on every listing ' +
      'site. It cannot tell us which property this listing is for. Try a photo of the actual ' +
      'unit — a window view or an odd corner works better than a show kitchen.',
  },
  no_addresses_found: {
    heading: 'No address to compare against',
    body:
      'These photos do appear elsewhere, but none of those pages names a street address, so there is ' +
      'nothing to check yours against. That is not a red flag by itself, and not a pass either.',
  },
};

const ERRORS: Record<string, string> = {
  invalid_token: 'That upload is no longer valid. Select the photo again.',
  rate_limited: 'Too many checks from this address. Try again in a little while.',
  quota: 'The search quota for this demo is exhausted. Try again next month.',
  auth: 'The search service rejected our credentials. This is our problem, not yours.',
  transport: 'The search service did not respond. Try again in a moment.',
  unknown: 'The search service returned something we could not read.',
  not_configured: 'This deployment is missing its API configuration.',
  invalid_image_url: 'That image is not one we stored. Upload the photo again.',
  address_too_long: 'That address is too long. Enter just the street address.',
  unsupported_type: 'Upload a JPEG, PNG, or WebP photo.',
  too_large: 'That photo is too large. 4 MB is the limit.',
  length_required: 'The upload was rejected. Try selecting the photo again.',
  empty: 'That file appears to be empty.',
  storage_unavailable: 'We could not store the photo. Try again in a moment.',
  bad_request: 'Something about that request was malformed.',
};

function message(code: unknown): string {
  return (typeof code === 'string' && ERRORS[code]) || 'Something went wrong. Try again.';
}

/**
 * Parse a response body that may not be JSON at all.
 *
 * Platform errors — a 413 raised above the app, a gateway 502, a framework
 * error page — arrive as HTML. Letting `.json()` throw sent those to the
 * network-failure branch, telling people to check a connection that was fine.
 */
async function readJson(res: Response): Promise<{ [k: string]: unknown } | null> {
  try {
    return (await res.json()) as { [k: string]: unknown };
  } catch {
    return null;
  }
}

export default function Home() {
  const [file, setFile] = useState<File | null>(null);
  const [address, setAddress] = useState('');
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [result, setResult] = useState<Analysis | null>(null);
  /** The address the displayed result was checked against, not the live field. */
  const [checked, setChecked] = useState('');

  // Derived once per file, not once per render. Called inline in the JSX it
  // minted a new object URL on every keystroke, each one pinning the whole File
  // until the page unloaded.
  const previewUrl = useMemo(() => (file ? URL.createObjectURL(file) : null), [file]);
  useEffect(() => {
    if (!previewUrl) return;
    return () => URL.revokeObjectURL(previewUrl);
  }, [previewUrl]);

  // The listings naming the claimed address ARE the answer; the other eighty
  // are context. Split with the same matcher the server classified on, against
  // the address that was actually checked rather than whatever is in the box
  // now, so the split can never disagree with the counts shown beside it.
  const { named, others } = useMemo(() => {
    const rows = result?.matches ?? [];
    const names = (m: Evidence) => m.title !== '' && addressAppearsIn([m.title], checked) > 0;
    return { named: rows.filter(names), others: rows.filter((m) => !names(m)) };
  }, [result, checked]);

  function rows(list: Evidence[]) {
    return list.map((m, i) => (
      <li key={`${m.link}-${i}`}>
        {m.link ? (
          <a href={m.link} target="_blank" rel="noreferrer noopener">
            {m.title || m.link}
          </a>
        ) : (
          <span>{m.title}</span>
        )}
        {m.source && <span className="src">{m.source}</span>}
      </li>
    ));
  }

  async function check(e: React.FormEvent) {
    e.preventDefault();
    if (!file) return;

    setBusy(true);
    setError(null);
    setResult(null);
    setChecked(address);

    try {
      // The photo is stored first because Google Lens takes a URL and cannot be
      // handed an upload; /api/analyze deletes the blob once the lookup returns.
      const stored = await fetch('/api/upload', { method: 'POST', body: file });
      if (!stored.ok) {
        const body = await readJson(stored);
        // A 413 raised by the platform has no JSON body to name the cause, but
        // the status alone is enough to say the right thing.
        setError(message(body?.error ?? (stored.status === 413 ? 'too_large' : undefined)));
        return;
      }
      const blob = await readJson(stored);
      if (typeof blob?.url !== 'string') {
        setError(message(undefined));
        return;
      }

      const res = await fetch('/api/analyze', {
        method: 'POST',
        headers: { 'content-type': 'application/json' },
        body: JSON.stringify({ imageUrl: blob.url, token: blob.token, address }),
      });
      if (!res.ok) {
        const body = await readJson(res);
        setError(message(body?.error));
        return;
      }
      const data = await readJson(res);
      if (!data) {
        setError(message(undefined));
        return;
      }
      setResult(data as unknown as Analysis);
    } catch {
      setError('Could not reach the server. Check your connection and try again.');
    } finally {
      setBusy(false);
    }
  }

  return (
    <main>
      <header className="masthead">
        <p className="wordmark">DepositCheck</p>
        <p className="filed">Reverse image check · SerpApi</p>
      </header>

      <h1>
        Do these photos
        <span className="turn">belong to that address?</span>
      </h1>
      <p className="lede">
        Scammers relist someone else&rsquo;s photos under an address they do not own. Check where
        the photos already live before you wire a deposit.
      </p>

      <form onSubmit={check}>
        <p className="exhibit">
          <label className="exhibit-label" htmlFor="photo">
            Listing photo
            <span className="hint">Screenshot or save one image from the listing.</span>
          </label>
          <span className={previewUrl ? 'dropzone filled' : 'dropzone'}>
            <input
              id="photo"
              type="file"
              accept="image/jpeg,image/png,image/webp"
              required
              onChange={(e) => setFile(e.target.files?.[0] ?? null)}
            />
            {previewUrl ? (
              <>
                {/* eslint-disable-next-line @next/next/no-img-element -- a local object URL, not a remote asset */}
                <img className="preview" src={previewUrl} alt="The photo you selected" />
                <span className="replace">Choose a different photo</span>
              </>
            ) : (
              <>
                <strong>Choose a photo</strong>
                <span>JPEG, PNG or WebP · up to 4 MB</span>
              </>
            )}
          </span>
        </p>

        <div className="field">
          <label className="field-label" htmlFor="address">
            Address you were given
            <span className="hint">The street number and street name are what get compared.</span>
          </label>
          <input
            id="address"
            type="text"
            // The file input was required and this one was not, so the commonest
            // way to reach the server with nothing to compare was one click away.
            required
            maxLength={200}
            placeholder="13505 Burnet Rd, Austin TX"
            value={address}
            onChange={(e) => setAddress(e.target.value)}
          />

          <button type="submit" disabled={busy || !file}>
            {busy ? 'Checking…' : 'Check this listing'}
          </button>

          <p className="method">
            The photo is stored just long enough for the reverse image search to read it, then
            deleted.
          </p>
        </div>
      </form>

      {error && <p className="error">{error}</p>}

      {result && (
        <>
          <section className="result" data-verdict={result.verdict}>
            <p className="stamp">{result.verdict}</p>
            <h2>{(result.reason ? REASON_COPY[result.reason] : COPY[result.verdict]).heading}</h2>
            <p>{(result.reason ? REASON_COPY[result.reason] : COPY[result.verdict]).body}</p>
            {result.contradictingAddress && (
              <p className="competing">
                Found published as <strong>{result.contradictingAddress}</strong>
              </p>
            )}
          </section>

          {result.reason !== 'unreadable_address' && result.matches.length > 0 && (
            <dl className="tally">
              <div>
                <dt>Copies of this photo</dt>
                <dd>{result.matches.length}</dd>
              </div>
              <div>
                <dt>Sites carrying it</dt>
                <dd>{result.sourceCount}</dd>
              </div>
              <div>
                <dt>Naming your address</dt>
                <dd>{result.addressHits}</dd>
              </div>
            </dl>
          )}

          {result.reason !== 'unreadable_address' && result.matches.length > 0 && (
            <section className="evidence">
              {named.length > 0 && (
                <>
                  <h3>Listings that name your address</h3>
                  <ol className="named">{rows(named)}</ol>
                </>
              )}

              {/* Always folded. Opening eighty rows was the old failure: it read
                  as a data dump and buried the three rows that answer the
                  question. The count in the summary is the honest headline. */}
              <details>
                <summary>
                  {named.length > 0 ? 'Everywhere else this photo appears' : 'Where this photo appears'}{' '}
                  ({others.length})
                </summary>
                <ol>{rows(others)}</ol>
              </details>

              <p className="note">
                Each link opens the page carrying the photo, so you can read the address it was
                published under yourself.
              </p>
            </section>
          )}
        </>
      )}
    </main>
  );
}
